### ISSUE TITLE
Implement validation in ResolverMap

### ISSUE THREAD

**Issue by MrHardcode** [Hold-Krykke/Security_and_FullstackJavascript_Exam#39]
Right now we're not really doing much to protect our GraphQL queries and mutations. We can implement validation using `context` pretty easily.

Right now "Valid" and "Token" are on context. 
Token, however, only contains email. 
I will use facade "getUserByEmail" to check if email in token exists in database, and is tied to the one being requested deleted, or position updated. Will make a function for that. Currently doing so. 

- [x] Someone can update another person. That shouldnt be allowed, right? Should only be able to update your own? We need to check for that somehow. 
![image](https://user-images.githubusercontent.com/11192971/83279132-ec6e1f00-a1d4-11ea-9d25-fc875496372b.png)

- [x] Someone can delete another user. Should only be able to delete your own account, right? We need to check for that somehow. Right now you can log in, then delete anyone. 
![image](https://user-images.githubusercontent.com/11192971/83279252-217a7180-a1d5-11ea-99d5-4f649017eebf.png)

**Comment by MalteMagnussen** [comment]
> We can implement validation using `context` pretty easily.

Yeah :) That's why its designed like that. You do the authentication in the context handler in the server creation in `server.ts`. 
![image](https://user-images.githubusercontent.com/11192971/83231293-91640a00-a18b-11ea-81cf-0f7d9da9e796.png)
You can place whatever you want on context here. 

Then in the resolver, you can decide authorization, and protect endpoints. 
![image](https://user-images.githubusercontent.com/11192971/83231367-ae98d880-a18b-11ea-95bd-08324a9ce7d2.png)
Like for example this. You can check context for whatever :) And then throw one of Apollos own errors. 
Authentication if user is not logged in, authorization if user doesnt have permission,

**Comment by MalteMagnussen** [comment]
What should be protected? 
Or maybe its easier to say, what shouldnt be protected in the resolverMap? 

I'm making a branch for this.

**Comment by MalteMagnussen** [comment]
The Branch for the issue: https://github.com/Hold-Krykke/Security_and_FullstackJavascript_Exam/tree/ProtectedRoutes
